services:
  - type: web
    name: backend
    env: node
    plan: free
    buildCommand: npm ci && npm rebuild bcrypt --build-from-source
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: false
    autoDeploy: false
